backend:
  name: git-gateway
  branch: main

media_folder: "site/static/img"
public_folder: "img"

collections:
  # Collection for Individual Blog Posts
  - name: "post"
    label: "Blog Posts" # Renamed for clarity
    folder: "site/content/post"
    # This filter line is crucial. It tells this collection to IGNORE the _index.md file.
    filter: {field: "path",- value: "site/content/post/_index.md"}
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}

  # Collection for the Main Site Pages
  - name: "pages"
    label: "Site Pages"
    files:
      - file: "site/content/_index.md"
        label: "Home Page"
        name: "home"
        fields:
          # ... (Your Home Page fields) ...
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - label: "Homepage Gallery"
            name: gallery
            widget: object
            fields:
              - {label: "Heading", name: "heading", widget: string}
              - {label: "Subheading", name: "subheading", widget: string}
              - {label: "Button Text", name: "buttonText", widget: string}
              - {label: "Button Link", name: "buttonLink", widget: string}
              - label: "Images"
                name: images
                widget: list
                field: {label: "Image", name: "image", widget: "image"}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget:string},
              {label: "Text", name: "text", widget: "text"}]}

      - file: "site/content/contact/_index.md"
        label: "About Us Page"
        name: "about"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}

      - file: "site/content/products/_index.md"
        label: "Services Page"
        name: "products"
        fields:
          - {label: Title, name: title, widget: string}
          - label: Intro
            name: intro
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Subheading, name: subheading, widget: string}
              - label: Blurbs
                name: blurbs
                widget: list
                fields:
                  - {label: Image, name: image, widget: image}
                  - {label: Text, name: text, widget: text}
      
      # This is the NEW DEDICATED entry for your Gallery Page
      - file: "site/content/post/_index.md"
        label: "Gallery Page"
        name: "gallery-page"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - label: "Gallery"
            name: gallery
            widget: object
            fields:
              - {label: "Heading", name: "heading", widget: string}
              - {label: "Subheading", name: "subheading", widget: string}
              - label: "Images"
                name: images
                widget: list
                field: {label: "Image", name: "image", widget: "image"}

  - name: "site_settings"
    label: "Site Settings"
    # ... (Your Site Settings fields) ...
    files:
      - file: "site/hugo.toml"
        label: "Hugo Config"
        name: "config"
        editor:
          preview: false
        fields:
          - {label: Site Title for Browser Tab, name: title, widget: string}
          - label: Params
            name: params
            widget: object
            fields:
              - label: Open Graph Image
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
